# Generated by Django 5.0 on 2024-01-10 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_itemcarrito_cliente_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='cliente',
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.cliente')),
                ('productos', models.ManyToManyField(through='productos.ItemCarrito', to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.carrito'),
        ),
    ]
